### ISSUE TITLE
Service status check - false negative for non-systemd services.

### ISSUE THREAD

**Issue by dschaper** [hetrixtools/agent#13]
Using Agent v1.5.2. 

It looks like #11 introduced `command -v systemctl` which is nice, but the pattern for checking will report a false down state for services that are not started via systemd service files. Services that are part of a docker stack are orchestrated via the docker service and are seen with the `ps` code block, but the `ps` code is not called since the `systemctl is-active` block finds the service is not active as it's not managed by systemctl.

Possible solution would be to conditionally invoke the `systemctl is-active` block. Could call `systemctl list-unit-files` and inverse grep the returned list for an associated service file. Or `systemctl list-unit-files <service_name>.service` to get the state. If that call returned `0 unit files listed` then it's not a systemctl managed service and should instead be checked via the older `ps` block.

**Comment by hetrixtools** [comment]
Hello,

We've done some tests and it seems that #14 will address this issue.
Can you please check if it fixes this particular issue in your case?

Thanks for reporting this issue.

**Comment by dschaper** [comment]
LGTM, thanks for the quick response!
