### ISSUE TITLE
Apply shellcheck.net recommendations

### ISSUE THREAD

**Issue by sebastianopilla** [hetrixtools/agent#21]
There are some issues with the bash script for the agent, mostly around quoting of variables and potential execution of command output. I suggest to implement the recommendations from https://www.shellcheck.net/ to improve the general quality and safety of the script.

**Comment by hetrixtools** [comment]
Thank you for the suggestion, we will look into making these changes.

**Comment by hetrixtools** [comment]
Implemented in https://github.com/hetrixtools/agent/commit/78077579a9ea2b840b4c518f445c9f1f3bc36c02
Thank you for your contribution and feedback.

**Comment by JeDaYoshi** [comment]
@hetrixtools This should be looked at again now that we're on v2 - it throws in a few suggestions.
