### ISSUE TITLE
Excessive CPU usage on an armv8 system (Raspi 4B)

### ISSUE THREAD

**Issue by CaldeiraG** [hetrixtools/agent#36]
I'm running Ubuntu Server 21.04 on my 4GB ram raspberry pi and every couple of days, the agent spikes up in CPU usage.

![htop done on raspberry](https://cdn.caldeirag.xyz/ShareX/2021/09/MobaXterm_XL1Dm7nBAn.png)

Rebooting fixes the issue temporarily until it spikes up again. 

I do not have any NAS or similar mounted in the raspberry as [this issue](https://github.com/hetrixtools/agent/issues/34) suggests.

Any thoughts?

**Comment by hetrixtools** [comment]
Hello,

Thank you for reporting this issue.

It looks like some very old agent processes are stuck and start causing high CPU usage for some reason.

We'll try to recreate this issue and implement some failsafe mechanism to prevent lingering agent processes on the system.

**Comment by CaldeiraG** [comment]
Any updates on this?

**Comment by hetrixtools** [comment]
Sorry for the late reply, we've applied a fix for this to our agent. Can you please upgrade and see if the problem still persists for your case?
Thank you.

**Comment by CaldeiraG** [comment]
Hello there, I used your hetrixtools_update.sh script you guys created to bump to the new version but the issue seems to remain, am I doing something wrong or should I just copy the new agent into `/etc/hetrixtools`? 

Thanks

**Comment by hetrixtools** [comment]
Yes, the update script should do the job of updating your agent to the latest version just fine.

But just to be sure, you can check if your agent file contains the new code:
```
for PID in `ps -ef | grep "hetrixtools_agent.sh" | awk '{print $2}'`
do
	PID_TIME=$(ps -p $PID -oetime= | tr '-' ':' | awk -F: '{ total=0; m=1; } { for (i=0; i < NF; i++) {total += $(NF-i)*m; m *= i >= 2 ? 24 : 60 }} {print total}')
	if [ ! -z "$PID_TIME" ] && [ "$PID_TIME" -ge 120 ]
	then
		kill -9 $PID
	fi
done
```

**Comment by CaldeiraG** [comment]
Hello there, I checked and it's running the latest version of the agent but the issue seems to persist.

![htop image](https://cdn.caldeirag.xyz/ShareX/2021/11/MobaXterm_jAK8nHtslu.png)

Thanks for the help so far.

**Comment by CaldeiraG** [comment]
Since I decided to move on from Ubuntu to Raspberry Pi OS Lite due to this issue and many others, it does not make sense to diagnose further. Thanks for the help.
