### ISSUE TITLE
[FEATURE] Log to multiple instances

### ISSUE THREAD

**Issue by foxycode** [hetrixtools/agent#4]
My customer have it's own account on HetrixTools. I'd like to send metrics both to his and my account. Is is possible or can you implement it?

**Comment by hetrixtools** [comment]
It's currently not possible, but we'll note it down on our suggestions list to be considered for future development.

In the meantime you can make the Server Monitor stats public on your Uptime Report, and share that Uptime Report with your customer:
https://docs.hetrixtools.com/resource-usage-privacy/
That way you can both have access and read the same monitoring stats of that one particular server.
