### ISSUE TITLE
Don't know how to restart agent

### ISSUE THREAD

**Issue by foxycode** [hetrixtools/agent#5]
I have read docs, but don't know how to restart agent. There is no rc script or service definition. How can I restart agent after adding services? How running agent again after fall is handled?

**Comment by hetrixtools** [comment]
The agent runs every minute on a cronjob, so there is nothing to restart.
You can re-install the agent, if you wish, by running the install code again.

**Comment by foxycode** [comment]
Not necesarry. Just didn't know about cron job. Thanks.
